# Generated by Django 4.1.1 on 2023-06-13 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='zio_code',
            new_name='zip_code',
        ),
    ]
